const monthOfBirth="January";
const firstName="Jason";
const lastName="McRae";
let city;
let age;
let nextCity;
city="Saskatoon";
age="40";
nextCity=city;
console.log('month of birth: ', monthOfBirth);
console.log(`full name: ${firstName},${lastName}`);